export const errorCodeMap = {
  2002: 'Import failed due to field mismatch.',
  2012: 'Import failed due to invalid employee id.',
  2013: 'Import failed due to invalid year.',
  2032: 'Import failed due to missing date field.',
  2006: 'Import failed due to duplicate employee id.',
  2009: 'Import failed due to invalid date format.',
  1101: 'Import failed due to incorrect role.',
  1105: 'Import failed due invalid name.',
  2004: 'Import failed due to invalid email id.',
  2008: 'Import failed due to invalid experience.',
  2024: 'Import failed due to invalid experience.',
  2025: 'Import failed due to invalid month.',
  2007: 'Import failed due to invalid employee id.',
  2005: 'Import failed because the email id already exists.',
  1003: 'Import failed due to incorrect date.',
  2105: 'There are conflicting requests for the resource within the project.',
  2014: 'Import failed because employee id is not between 4 - 8 characters',
  2010: 'Import failed due to unknown department.',
  2020: 'Import failed name required.',
  2023: 'Import failed because of missing Employee id.',
  2116: `Allocation cannot be deleted as it's already in progress.`,
  2075: 'Import failed due to invalid header',
  2076: 'Import failed because experience in year field exceeds maximum limit',
  2015: 'Import failed because name should only be alphabets',
  2016: 'Import failed because name should  be less than 50 characters',
  2019: 'Import failed email required',
  2021: 'Import failed department required',
  2022: 'Import failed role required',
  2026: 'Import failed because experience in month is not between 0 - 11',
  2027: 'Import failed due to invalid department',
  2028: 'Import failed due to invalid role',
  2029: 'Import failed due to invalid email',
  2035: 'Import failed because joining date needs to be need present or past date',
  2040: 'Import failed due to incorrect file type',
  2030: 'Import failed due to missing discription',
  2031: 'Import failed due to missing day field',
  2033: 'Import failed due to invalid date',
  2037: `Import failed because the date in the field isn't unique`,
  2039: `Imported file is empty`,
  2038: `Import failed becaue description in field is not unique`,
  2034: 'Import failed due to invalid date',
  2003: 'Import failed date required',
  2036: 'Import failed due to invalid date',
  1084: 'Provided email id already exist',
  1010: 'Unable to perform this action',
  1011: 'Invalid file size.',
  2000: 'Invalid file',
  1302: 'Project request send successfully',
  1348: 'Project updated successfully',
  1355: 'Project approved, Allocation wont be possible until project details are completed',
  1323: 'Project approved',
  1321: 'Project request does not exist anymore ',
  2119: 'Cannot delete the resource as it is allocated already.',
  2044: 'Please select at least one skill before submitting a technology-wise request.',
  2106: 'Request does not exist anymore',
  2110: 'Reject reason max limit (1000 characters) reached ',
};
